### ISSUE TITLE
Error on docker-compose on a raspi4

### ISSUE THREAD

**Issue by raetsch** [whatl3y/jupiter-git#2]
Hi,

i tried to get it running on a raspberry PI,

during creation of the container with docker-compose up, the following message came up:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

at the end stopps with this message:
web_1  | > jupiter-git@0.0.1 start /usr/jupiter-git
web_1  | > node dist/bin/jupiter-git.js
web_1  |
web_1  | internal/modules/cjs/loader.js:883
web_1  |   throw err;
web_1  |   ^
web_1  |
web_1  | Error: Cannot find module '/usr/jupiter-git/dist/bin/jupiter-git.js'
web_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js       :880:15)
web_1  |     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
web_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/ru       n_main.js:72:12)
web_1  |     at internal/main/run_main_module.js:17:47 {
web_1  |   code: 'MODULE_NOT_FOUND',
web_1  |   requireStack: []
web_1  | }
web_1  | npm ERR! code ELIFECYCLE
web_1  | npm ERR! errno 1
web_1  | npm ERR! jupiter-git@0.0.1 start: `node dist/bin/jupiter-git.js`
web_1  | npm ERR! Exit status 1
web_1  | npm ERR!
web_1  | npm ERR! Failed at the jupiter-git@0.0.1 start script.
web_1  | npm ERR! This is probably not a problem with npm. There is likely addit       ional logging output above.
web_1  |
web_1  | npm ERR! A complete log of this run can be found in:
web_1  | npm ERR!     /root/.npm/_logs/2021-03-22T23_27_30_155Z-debug.log
web_1  |
web_1  | > jupiter-git@0.0.1 start /usr/jupiter-git
web_1  | > node dist/bin/jupiter-git.js
web_1  |
web_1  | internal/modules/cjs/loader.js:883
web_1  |   throw err;
web_1  |   ^
web_1  |
web_1  | Error: Cannot find module '/usr/jupiter-git/dist/bin/jupiter-git.js'
web_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js       :880:15)
web_1  |     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
web_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/ru       n_main.js:72:12)
web_1  |     at internal/main/run_main_module.js:17:47 {
web_1  |   code: 'MODULE_NOT_FOUND',
web_1  |   requireStack: []
web_1  | }
web_1  | npm ERR! code ELIFECYCLE
web_1  | npm ERR! errno 1
web_1  | npm ERR! jupiter-git@0.0.1 start: `node dist/bin/jupiter-git.js`
web_1  | npm ERR! Exit status 1
web_1  | npm ERR!
web_1  | npm ERR! Failed at the jupiter-git@0.0.1 start script.
web_1  | npm ERR! This is probably not a problem with npm. There is likely addit       ional logging output above.
web_1  |
web_1  | npm ERR! A complete log of this run can be found in:
web_1  | npm ERR!     /root/.npm/_logs/2021-03-22T23_27_59_71

System is:
uname -a
Linux raspi4 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

regards
raetsch

**Comment by whatl3y** [comment]
Thanks for submitting @raetsch! Can you provide the entire output you get when the container builds? i.e. all Dockerfile instructions and the respective output from each?

**Comment by raetsch** [comment]
Hi @whatl3y,

i just retried on a VM with ubuntu 18.04 and have the same issue.
here is the complete (hopefully) output:
Creating network "jupitergit_default" with the default driver
Building web
Step 1/8 : FROM node:14.16.0
14.16.0: Pulling from library/node
16cf3fa6cb11: Pull complete
3ddd031622b3: Pull complete
69c3fcab77df: Pull complete
a403cc031cae: Pull complete
b900c5ffbaf4: Pull complete
f877dc3acfca: Pull complete
37e7c47402dc: Pull complete
880eb09060dd: Pull complete
36731974ae02: Pull complete
Digest: sha256:fe842f5b828c121514d62cbe0ace0927aec4f3130297180c3343e54e7ae97362
Status: Downloaded newer image for node:14.16.0
 ---> e2885a998904
Step 2/8 : LABEL AUTHOR="Lance Whatley"
 ---> Running in 7d1396aec40c
Removing intermediate container 7d1396aec40c
 ---> 06784e4052f9
Step 3/8 : WORKDIR /usr/jupiter-git
 ---> Running in 3224d6e0e72c
Removing intermediate container 3224d6e0e72c
 ---> fe21eb841f98
Step 4/8 : COPY package.json .
 ---> 8bf2d4848557
Step 5/8 : RUN npm install --no-package-lock
 ---> Running in 0dd516402834

> dtrace-provider@0.8.8 install /usr/jupiter-git/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

make: Entering directory '/usr/jupiter-git/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/usr/jupiter-git/node_modules/dtrace-provider/build'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 210 packages from 258 contributors and audited 212 packages in 6.289s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Removing intermediate container 0dd516402834
 ---> 4788696e2253
Step 6/8 : COPY . .
 ---> 617fa0ddd172
Step 7/8 : RUN npm run build
 ---> Running in 58b0f8327516

> jupiter-git@0.0.1 build /usr/jupiter-git
> npx tsc

Removing intermediate container 58b0f8327516
 ---> dc4543f986c9
Step 8/8 : CMD npm start
 ---> Running in 5b507142c43c
Removing intermediate container 5b507142c43c
 ---> 8f7fd9153927
Successfully built 8f7fd9153927
Successfully tagged jupitergit_web:latest
WARNING: Image for service web was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating jupitergit_web_1 ... 
Creating jupitergit_web_1 ... done
Attaching to jupitergit_web_1
web_1  | 
web_1  | > jupiter-git@0.0.1 start /usr/jupiter-git
web_1  | > node dist/bin/jupiter-git.js
web_1  | 
web_1  | internal/modules/cjs/loader.js:883
web_1  |   throw err;
web_1  |   ^
web_1  | 
web_1  | Error: Cannot find module '/usr/jupiter-git/dist/bin/jupiter-git.js'
web_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
web_1  |     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
web_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
web_1  |     at internal/main/run_main_module.js:17:47 {
web_1  |   code: 'MODULE_NOT_FOUND',
web_1  |   requireStack: []
web_1  | }
web_1  | npm ERR! code ELIFECYCLE
web_1  | npm ERR! errno 1
web_1  | npm ERR! jupiter-git@0.0.1 start: `node dist/bin/jupiter-git.js`
web_1  | npm ERR! Exit status 1
web_1  | npm ERR! 
web_1  | npm ERR! Failed at the jupiter-git@0.0.1 start script.
web_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
web_1  | 
web_1  | npm ERR! A complete log of this run can be found in:
web_1  | npm ERR!     /root/.npm/_logs/2021-03-23T21_01_30_110Z-debug.log
jupitergit_web_1 exited with code 1


regards
raetsch

**Comment by whatl3y** [comment]
Ahh yes wow I apologize! The `docker-compose.yml` was mapping a volume to the host machine instead of using the built `dist` in the container (this is useful in dev so you don't have to rebuild the container each time you make a change).

The following commit resolves this, so you can `git pull` or re-clone the latest master branch and it should work as expected. If you'd like to do dev you should install node/npm on the host machine and `npm install && npm run build` on the host as well to create a local `dist` that will be used instead, in addition to using the `-f docker-compose.dev.yml` in your docker-compose up command. Otherwise, ignore :) 

https://github.com/whatl3y/jupiter-git/commit/6a42b5a2e42225cd6ec2452ddeb26b1f35f8ec46
